#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/xdebug.ini /etc/php5/mods-available/xdebug.ini 2.2.0-1~ -- "$@"
# End automatically added section
