#!/bin/sh
set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/xdebug.ini \
		/etc/php5/mods-available/xdebug.ini 2.2.0-1~ -- "$@"
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
