#!/bin/sh
set -e

dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/xdebug.ini \
	/etc/php5/mods-available/xdebug.ini 2.2.0-1~ -- "$@"

case "$1" in
    install|upgrade)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
