#! /bin/sh

set -e

case "$1" in
  install|upgrade)
    if [ -n "$2" ] && dpkg --compare-versions "$2" lt 1.0.2-3
    then
      ucf --purge /etc/php5/conf.d/memcached.ini
    fi
    if test -e /etc/php5/conf.d/memcached.ini
    then
      sed s/^\;extension/extension/ -i /etc/php5/conf.d/memcached.ini
      dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/memcached.ini \
          /etc/php5/mods-available/memcached.ini 2.0.1-3 -- "$@"
      rm -f /etc/php5/conf.d/memcached.ini
    fi
    ;;
  abort-upgrade)
    ;;
  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac



exit 0
