#!/bin/sh
set -e
# Automatically added by dh_php5
if [ -e /usr/share/php5/php5-maintscript-helper ] ; then
    . /usr/share/php5/php5-maintscript-helper
    for conf in xdebug  ; do
        php5_invoke enmod ALL $conf || exit $?
    done
else
    for conf in xdebug  ; do
        php5enmod $conf
    done
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/xdebug.ini /etc/php5/mods-available/xdebug.ini 2.2.0-1~ -- "$@"
# End automatically added section
