#!/bin/sh

set -e

if [ "$1" = "triggered" ] && [ "$2" = "/etc/php5/fpm/conf.d" ]; then
    invoke-rc.d php5-fpm restart
fi

dpkg-maintscript-helper mv_conffile /etc/php5/fpm/main.conf /etc/php5/fpm/php-fpm.conf 5.3.5-1 -- "$@"

CONFDIR=/etc/php5/fpm/conf.d

if [ -L $CONFDIR ]; then
    rm $CONFDIR
    mkdir $CONFDIR
fi

if [ "$1" = "configure" ]; then
    phpini="/etc/php5/fpm/php.ini"

    if [ "fpm" = "cli" ]; then
	ucf /usr/share/php5/php.ini-production.fpm $phpini
    else
	ucf /usr/share/php5/php.ini-production $phpini
    fi
    ucfr php5-fpm $phpini

    if [ -e /usr/share/php5/php5-maintscript-helper ]; then
	. /usr/share/php5/php5-maintscript-helper
	
	mods=$(php5query -M)
	for mod in $mods; do
	    php5_invoke enmod fpm $mod
	done
    fi

fi

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask php5-fpm.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled php5-fpm.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable php5-fpm.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state php5-fpm.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/php5-fpm" ]; then
	update-rc.d php5-fpm defaults >/dev/null
	invoke-rc.d php5-fpm start || exit $?
fi
# End automatically added section


exit 0
