#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/php5_cgi.conf \
    /etc/apache2/conf-available/php5-cgi.conf 5.5.0~beta4-1 -- "$@"

dpkg-maintscript-helper rm_conffile /etc/apache2/mods-available/php5_cgi.load 5.5.0~beta4-1 -- "$@"

VERSION=$2

php5_enable() {
    # Enable php5-cgi only if upgrading from older versions of php5-cgi
    if [ -n "$VERSION" ] && dpkg --compare-versions "$VERSION" lt 5.4.4-5; then
	return 0
    else
	return 1
    fi
}

if [ "$1" = "configure" ]; then
    update-alternatives \
	--install /usr/bin/php-cgi php-cgi /usr/bin/php5-cgi 50 \
	--slave /usr/share/man/man1/php-cgi.1.gz php-cgi.1.gz \
	/usr/share/man/man1/php5-cgi.1.gz

    update-alternatives \
	--install /usr/lib/cgi-bin/php php-cgi-bin /usr/lib/cgi-bin/php5 50
fi

CONFDIR=/etc/php5/cgi/conf.d

if [ -L $CONFDIR ]; then
    rm $CONFDIR
    mkdir $CONFDIR
fi

if [ "$1" = "configure" ]; then
    phpini="/etc/php5/cgi/php.ini"

    if [ "cgi" = "cli" ]; then
	ucf /usr/share/php5/php.ini-production.cgi $phpini
    else
	ucf /usr/share/php5/php.ini-production $phpini
    fi
    ucfr php5-cgi $phpini

    if [ -e /usr/share/php5/php5-maintscript-helper ]; then
	. /usr/share/php5/php5-maintscript-helper
	
	mods=$(php5query -M)
	for mod in $mods; do
	    php5_invoke enmod cgi $mod
	done
    fi

fi

# Automatically added by dh_apache2
if php5_enable; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		for conf in php5-cgi  ; do
			apache2_invoke enconf $conf  || exit $?
		done
	fi
fi
# End automatically added section


exit 0
