#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
    update-alternatives --remove php-cgi /usr/bin/php5-cgi
    update-alternatives --remove php-cgi-bin /usr/lib/cgi-bin/php5
fi

php5_enable() { return 0; }

if [ -e /usr/share/php5/php5-maintscript-helper ]; then
    . /usr/share/php5/php5-maintscript-helper

    mods=$(php5query -M)
    for mod in $mods; do
	php5_invoke dismod cgi $mod
    done
fi

# Automatically added by dh_apache2
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
	if php5_enable; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in php5-cgi  ; do
				apache2_invoke disconf $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section


exit 0
