#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile /etc/php5/fpm/main.conf /etc/php5/fpm/php-fpm.conf 5.3.5-1 -- "$@"

php5_enable() { return 0; }

if [ "$1" = "purge" ]; then
    phpini=/etc/php5/fpm/php.ini
    # remove the flag to remember the original state
    if [ -e /etc/php5/fpm/.start ]; then
	rm -f /etc/php5/fpm/.start
    fi
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
	rm -f $phpini$ext
    done
    rm -f $phpini
    if which ucf >/dev/null; then
	ucf --purge $phpini
    fi
    if which ucfr >/dev/null; then
	ucfr --purge php5-fpm $phpini
    fi
fi

if [ -e /usr/share/php5/php5-maintscript-helper ]; then
    . /usr/share/php5/php5-maintscript-helper

    mods=$(php5query -M)
    for mod in $mods; do
	php5_invoke dismod fpm $mod
    done
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d php5-fpm remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask php5-fpm.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge php5-fpm.service >/dev/null
		deb-systemd-helper unmask php5-fpm.service >/dev/null
	fi
fi
# End automatically added section


exit 0
